name: example_CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rouler les tests unitaires
        run: |
          cd src
          python3 -m pytest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: activate webhook
        run: curl -X POST 10.194.32.213:9000/hooks/redeploy-lab0.sh